### ISSUE TITLE
Add edwards448 M, N

### ISSUE THREAD

**Issue by greghudson** [kaduk/spake2#2]
I'm recording the generated values here since I don't have time right at this moment to make a proper pull request.  I constructed these using my own Python elliptic curve code and verified them with the Edwards curve implementations in RFC 8032 appendix A.  The Python M/N generation code in the draft needs to be modified to know how to canonicalize an edwards448 point string, as does the English text.  It might also be nice to write the Python code so it plugs cleanly into the RFC 8032 Python code instead of mine, although of course that would only work for the Edwards curves and not the NIST ones.

For edwards448, M was found in 2 iterations, N in 16 iterations.

M =                                                                             
b6221038a775ecd007a4e4dde39fd76ae91d3cf0cc92be8f0c2fa6d6b66f9a12942f5a92646109152292464f3e63d354701c7848d9fc3b8880
seed: edwards448 point generation seed (M)                                    
                                                                                
N =                                                                             
6034c65b66e4cd7a49b0edec3e3c9ccc4588afd8cf324e29f0a84a072531c4dbf97ff9af195ed714a689251f08f8e06e2d1f24a0ffc0146600
seed: edwards448 point generation seed (N)

**Comment by kaduk** [comment]
closed via #3 (also from you); thanks again
