### ISSUE TITLE
Remove requirement on using a password hashing function

### ISSUE THREAD

**Issue by vasilvv** [kaduk/spake2#7]
Currently, the spec requires that some password-hashing function is used.  This is important when SPAKE2 is used for authentication using long-term passwords, but gets in a way when the password is ephemeral (e.g. a PIN used to pair a low-powered device).  I'd prefer we remove it or define an scrypt-less profile.

**Comment by wbl** [comment]
Please email the CFRG mailing list: this seems beyond an editorial comment.
